### ISSUE TITLE
Fix blog 404 blog pages

### ISSUE THREAD

**Issue by 7alip** [freedomcombination/monorepo#1194]
Blog pages return 404 not found in production.

Example url: https://www.freedomcombination.com/blog/reaching-integration

Backend data for this blog:

<img width="2053" alt="Screenshot 2024-04-16 at 00 28 10" src="https://github.com/freedomcombination/monorepo/assets/22167684/2718dbf3-4ec8-426b-9307-e5e9db0aba49">

Why does the page end up with a not found page even though the data is published and approved?.

See apps/foundation/pages/blog/[slug].tsx

```tsx
  const blog = queryClient.getQueryData<Blog>(queryKey)

  if (!blog) return { notFound: true }
  ```

**Comment by bbluechip** [comment]
Can I get detailed information about this issue?

**Comment by 7alip** [comment]
@bbluechip I updated the description

**Comment by myniqx** [comment]
this is interesting, because its work on dev : 
![image](https://github.com/freedomcombination/monorepo/assets/4520739/fd2ee67f-3d08-403c-8695-e3b7bdff0487)

@7alip it is so confusing, storybook is not working on my system, but it runs on yours. and this is something new. its run on my dev but not run on production. how can we debug this while its running without any error.

**Comment by 7alip** [comment]
> this is interesting, because it works on dev :

@myniqx We can try running next production start locally if it's possible with this monorepo. Otherwise  We can log inside serverSideProps and listen it from Vercel logs after pushing the branch.

**Comment by 7alip** [comment]
@myniqx It was because of 401 error when the token is undefined:

```ts
headers: { Authorization: "Bearer undefined" }
```
