### ISSUE TITLE
TEST: Profile Editing

### ISSUE THREAD

**Issue by ulgerf** [freedomcombination/monorepo#1661]
In Profile Editing, while updating the password, there is no warning about the required use of uppercase and lowercase letters as initially requested, and it accepts passwords without these requirements.

**Test Case ID:** TC00?

**Title:** Password Update Requirements Not Enforced in Profile Editing

**Description**: Verify that the Profile Editing section enforces password requirements, such as the use of uppercase and lowercase letters, and provides a warning if these requirements are not met.

**Steps:**

Navigate to the Profile Editing section.
Attempt to update the password without using uppercase or lowercase letters if these are required.
Save the changes.
Observe whether a warning is displayed about the required use of uppercase and lowercase letters.

**Expected Result:** A warning should be displayed if the password does not meet the requirements for uppercase and lowercase letters. The password should not be accepted without fulfilling these criteria.

**Comment by 7alip** [comment]
@hilalnigarbasan This test case can still be written because it does not change the password and only expects an error message when an invalid password is entered.

I made a [comment](https://github.com/freedomcombination/monorepo/pull/1674#discussion_r1769243473) before about it:

You could try giving invalid passwords like:

- Test123 (without symbol)
- test?123 (without uppercase)
- TEST?123 (without lowercase)
- Test?Test (without numbers)

You can create a new branch from the latest dev and write this test case
